name: Github Actions Debug

on:
    pull_request:
    push:
        branches:
            - develop

jobs:
    build:
        name: Running Units Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
            - name: Compose up the docker
              run: docker-compose -f "docker-compose.yml" up -d --build
